# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
